### ISSUE TITLE
wan22_svi_pro workflow crashes if I try to run any extension cells

### ISSUE THREAD

**Issue by maxmoudz** [vita-epfl/Stable-Video-Infinity#90]
Even with gguf models and memory arguments, it crashes after the initial cell with an OOM.  Using colab free environment with 12gb vram.

**Comment by mjzcng** [comment]
That sounds similar to a failure mode I saw when a long-video workflow kept all extension stages inside one ComfyUI prompt. I worked around it by saving each segment and its checkpoint to disk, ending the prompt, unloading models and clearing the execution cache, then requeueing the next segment as a fresh prompt.

I packaged the approach here: https://github.com/mjzcng/ComfyUI-MiniMaxH3-Disk-Relay

It is MiniMax H3-specific and will not plug into SVI/Wan 2.2 directly. If H3 is an option, it may be worth trying; otherwise the lifecycle may still be useful as a reference. With 12 GB VRAM I cannot promise it will fit—the project mainly addresses memory retained across segments, not the peak memory required by one segment.
